// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/authors/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authors/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authors/[id].put').default>>>>
    }
    '/api/authors/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authors/create.post').default>>>>
    }
    '/api/authors': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authors/index').default>>>>
    }
    '/api/books/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/books/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/books/[id].put').default>>>>
    }
    '/api/books/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/books/create.post').default>>>>
    }
    '/api/books': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/books/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}